//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoSalon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoSalon()
        {
            this.Automobils = new HashSet<Automobil>();
        }
    
        public int Id { get; set; }
        public int AutoKompanijaId { get; set; }
        public int BrojRaspolozivihAutomobila { get; set; }
        public string Grad { get; set; }
        public string Ulica { get; set; }
    
        public virtual AutoKompanija AutoKompanija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Automobil> Automobils { get; set; }
    }
}
