//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoKompanijaDbContext : DbContext
    {
        public AutoKompanijaDbContext()
            : base("name=AutoKompanijaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoKompanija> AutoKompanijas { get; set; }
        public virtual DbSet<AutoSalon> AutoSalons { get; set; }
        public virtual DbSet<Sluzbenik> Sluzbeniks { get; set; }
        public virtual DbSet<Kupac> Kupacs { get; set; }
        public virtual DbSet<Automobil> Automobils { get; set; }
        public virtual DbSet<Placanje> Placanjes { get; set; }
        public virtual DbSet<Zaposljava> Zaposljavas { get; set; }
        public virtual DbSet<Pregovara> Pregovaras { get; set; }
    }
}
