//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automobil()
        {
            this.Placanjes = new HashSet<Placanje>();
        }
    
        public int Id { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int Cena { get; set; }
        public Nullable<int> AutoSalonId { get; set; }
        public Nullable<int> KupacId { get; set; }
        public Nullable<System.DateTime> DatumNarucivanja { get; set; }
    
        public virtual AutoSalon AutoSalon { get; set; }
        public virtual Kupac Kupac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Placanje> Placanjes { get; set; }
    }
}
