//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placanje
    {
        public int Id { get; set; }
        public System.DateTime DatumPlacanja { get; set; }
        public int AutomobilId { get; set; }
    
        public virtual Automobil Automobil { get; set; }
    }
}
