//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregovara
    {
        public int SluzbenikId { get; set; }
        public int KupacId { get; set; }
    
        public virtual Sluzbenik Sluzbenik { get; set; }
        public virtual Kupac Kupac { get; set; }
    }
}
